name: Atualizar PKGBUILDs no AUR

on:
  schedule:
    - cron: "*/10 * * * *"  # Executa a cada 10 minutos
  push:
    branches:
      - main

jobs:
  atualizar-pkgbuilds:
    runs-on: ubuntu-latest
    container:
      image: archlinux/base:latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar yay
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm base-devel git
          git clone https://aur.archlinux.org/yay.git
          cd yay
          makepkg -si --noconfirm
          cd ..
          rm -rf yay

      - name: Atualizar repositórios
        run: yay -Syyu --noconfirm

      - name: Verificar atualizações e atualizar PKGBUILDs
        run: |
          for pkgbuild in packages/**/PKGBUILD; do
            yay -Sua --noconfirm --noremovemake --noredownload --nobuild --nocleanmenu "$pkgbuild"
          done
