name: Atualizar PKGBUILDs no AUR

on:
  schedule:
    - cron: "*/10 * * * *"  # Executa a cada 10 minutos
  push:
    branches:
      - main

jobs:
  atualizar-pkgbuilds:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Atualizar repositórios
        run: pacman -Syyu --noconfirm

      - name: Instalar yay
        run: |
          pacman -S --needed --noconfirm base-devel git
          useradd -m yay
          echo "yay ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/yay
          su -l yay -c "export BUILDDIR=/tmp && git clone https://aur.archlinux.org/yay.git"
          su -l yay -c "cd yay && export BUILDDIR=/tmp && sudo -u nobody makepkg -si --noconfirm"
          userdel -r yay

      - name: Verificar atualizações e atualizar PKGBUILDs
        run: |
          for pkgbuild in packages/**/PKGBUILD; do
            yay -Sua --noconfirm --noremovemake --noredownload --nobuild --nocleanmenu "$pkgbuild"
          done
