name: Update PKGBUILDs

on:
  schedule:
    - cron: "*/10 * * * *"  # Run every 10 minutes
  push:
    branches:
      - main

jobs:
  update-pkgbuilds:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create non-root user
        run: |
          useradd -m -G wheel pkgbuilder
          echo "pkgbuilder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Switch to non-root user
        run: |
          su - pkgbuilder

      - name: Update repositories
        run: pacman -Syyu --noconfirm

      - name: Install yay
        run: |
          pacman -S sudo
          sudo pacman -S --needed --noconfirm base-devel git
          git clone https://aur.archlinux.org/yay.git
          cd yay
          makepkg -si --noconfirm
          cd ..
          rm -rf yay

      - name: Check for updates and update PKGBUILDs
        run: |
          for pkgbuild in packages/**/PKGBUILD; do
            yay -Sua --noconfirm --noremovemake --noredownload --nobuild --nocleanmenu "$pkgbuild"
          done
